###########################################################
### Muah's Tech Blog - Beautiful Jekyll
###########################################################

# Use Beautiful Jekyll theme (GitHub Pages remote theme)
remote_theme: daattali/beautiful-jekyll

############################
# --- Required options --- #
############################

title: Lotimuah's Blog
author: 

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Categories: "tags"

################
# --- Logo --- #
################

avatar: "/assets/img/totoro.jpg"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "kwmg0754@gmail.com"
  github: Lotimuah


###########################
# --- General options --- #
###########################

share-links-active:
  twitter: false
  facebook: false
  linkedin: false
  vk: false
  reddit: false

url-pretty: "lotimuah.github.io"
repository: Lotimuah/Lotimuah.github.io
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: false
post_search: true
edit_page_button: false

######################################
# --- Colours / background image --- #
######################################

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# Custom CSS (Bold 굵기 줄이기)
site-css:
  - "/assets/css/custom.css"

################
# --- Misc --- #
################

date_format: "%B %-d, %Y"
timezone: "Asia/Seoul"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 10

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-github-metadata
